name: Servian App Build

on:
  push:
    branches:
      - main

env:
  REPONAME: ${{ github.event.repository.name }}
  WORKSPACE: ${{ github.workspace }}
  Administrator_login: ${{ secrets.ADMINISTRATOR_LOGIN}}
  client_id: ${{secrets.CLIENT_ID}}
  client_secret: ${{secrets.CLIENT_SECRET}}
  tenant_id: ${{secrets.SUBSCRIPTION_ID}}
  subscription_id: ${{secrets.TENANT_ID}}

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Print terraform version
        run: terraform version

      - name: Initalize Terraform
        run: terraform init

      - name: terraform plan
        run: terraform plan -var="administratorlogin=${{secrets.Administrator_login}}" -var="administratorloginpassword=${{secrets.Administrator_login_password}}" -var="client_id=${{secrets.client_id}}" -var="client_secret=${{secrets.client_secret}}" -var="tenant_id=${{secrets.tenant_id}}" -var="subscription_id=${{secrets.subscription_id}}" -out=tfplan

      - name: terraform apply
        run: terraform apply -auto-approve "tfplan"