name: Test Cron Job

on:
  workflow_dispatch:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"


jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Print terraform version
        run: terraform version